[package]
name = "my_rust_package"
edition = "2018"
version = "0.1.0"

[lib]
name = "my_rust_package"
crate-type = ["staticlib"] # Creates .a static lib.
# crate-type = ["cdylib"] # Creates .so dynamic lib.
path = "./src/lib.rs"

