[package]
name = "my_rust_package"
version = "0.1.0"
edition = "2021"

[lib]
name = "my_rust_package"
crate-type = ["staticlib"] # Creates .a static lib
# crate-type = ["cdylib"] # Creates .so dynamic lib

